package edu.fiu.ffqr.models;

import java.util.ArrayList;

public class ValidNutrientList {
	public static String[] validNutrients = {
			"Total Grams",
			"Energy (kcal)",
			"Total Fat (g)",
			"Total Carbohydrate (g)",
			"Total Protein (g)",
			"Animal Protein (g)",
			"Vegetable Protein (g)",
			"Alcohol (g)",
			"Cholesterol (mg)",
			"Total Saturated Fatty Acids (SFA) (g)",
			"Total Monounsaturated Fatty Acids (MUFA) (g)",
			"Total Polyunsaturated Fatty Acids (PUFA) (g)",
			"Fructose (g)",
			"Galactose (g)",
			"Glucose (g)",
			"Lactose (g)",
			"Maltose (g)",
			"Sucrose (g)",
			"Starch (g)",
			"Total Dietary Fiber (g)",
			"Soluble Dietary Fiber (g)",
			"Insoluble Dietary Fiber (g)",
			"Pectins (g)",
			"Total Vitamin A Activity (International Units) (IU)",
			"Beta-Carotene Equivalents (derived from provitamin A carotenoids) (mcg)",
			"Retinol (mcg)",
			"Vitamin D (calciferol) (mcg)",
			"Total Alpha-Tocopherol Equivalents (mg)",
			"Vitamin E (Total Alpha-Tocopherol) (mg)",
			"Beta-Tocopherol (mg)",
			"Gamma-Tocopherol (mg)",
			"Delta-Tocopherol (mg)",
			"Vitamin K (phylloquinone) (mcg)",
			"Vitamin C (ascorbic acid) (mg)",
			"Thiamin (vitamin B1) (mg)",
			"Riboflavin (vitamin B2) (mg)",
			"Niacin (vitamin B3) (mg)",
			"Pantothenic Acid (mg)",
			"Vitamin B-6 (pyridoxine, pyridoxyl, & pyridoxamine) (mg)",
			"Total Folate (mcg)",
			"Vitamin B-12 (cobalamin) (mcg)",
			"Calcium (mg)",
			"Phosphorus (mg)",
			"Magnesium (mg)",
			"Iron (mg)",
			"Zinc (mg)",
			"Copper (mg)",
			"Selenium (mcg)",
			"Sodium (mg)",
			"Potassium (mg)",
			"Tryptophan (g)",
			"Threonine (g)",
			"Isoleucine (g)",
			"Leucine (g)",
			"Lysine (g)",
			"Methionine (g)",
			"Cystine (g)",
			"Phenylalanine (g)",
			"Tyrosine (g)",
			"Valine (g)",
			"Arginine (g)",
			"Histidine (g)",
			"Alanine (g)",
			"Aspartic Acid (g)",
			"Glutamic Acid (g)",
			"Glycine (g)",
			"Proline (g)",
			"Serine (g)",
			"Aspartame (mg)",
			"Saccharin (mg)",
			"Caffeine (mg)",
			"Phytic Acid (mg)",
			"Oxalic Acid (mg)",
			"3-Methylhistidine (mg)",
			"Sucrose Polyester (g)",
			"Ash (g)",
			"Water (g)",
			"Total Vitamin A Activity (Retinol Equivalents) (mcg)",
			"Total Trans-Fatty Acids (TRANS) (g)",
			"Beta-Carotene (provitamin A carotenoid) (mcg)",
			"Alpha-Carotene (provitamin A carotenoid) (mcg)",
			"Beta-Cryptoxanthin (provitamin A carotenoid) (mcg)",
			"Lutein + Zeaxanthin (mcg)",
			"Lycopene (mcg)",
			"Dietary Folate Equivalents (mcg)",
			"Natural Folate (food folate) (mcg)",
			"Synthetic Folate (folic acid) (mcg)",
			"Total Vitamin A Activity (Retinol Activity Equivalents) (mcg)",
			"Energy (kj)",
			"Niacin Equivalents (mg)",
			"Total Sugars (g)",
			"Omega-3 Fatty Acids (g)",
			"Manganese (mg)",
			"Vitamin E (International Units) (IU)",
			"Natural Alpha-Tocopherol (RRR-alpha-tocopherol or d-alpha-tocopherol) (mg)",
			"Synthetic Alpha-Tocopherol (all rac-alpha-tocopherol or dl-alpha-tocopherol) (mg)",
			"Daidzein (mg)",
			"Genistein (mg)",
			"Glycitein (mg)",
			"Coumestrol (mg)",
			"Biochanin A (mg)",
			"Formononetin (mg)",
			"Added Sugars (by Available Carbohydrate) (g)",
			"Acesulfame Potassium (mg)",
			"Sucralose (mg)",
			"Available Carbohydrate (g)",
			"Choline (mg)",
			"Betaine (mg)",
			"Erythritol (g)",
			"Inositol (g)",
			"Isomalt (g)",
			"Lactitol (g)",
			"Maltitol (g)",
			"Mannitol (g)",
			"Pinitol (g)",
			"Sorbitol (g)",
			"Xylitol (g)",
			"Nitrogen (g)",
			"Tagatose (mg)",
			"Vitamin D2 (ergocalciferol) (mcg)",
			"Vitamin D3 (cholecalciferol) (mcg)",
			"Added Sugars (by Total Sugars) (g)",
			"Total Grains (ounce equivalents)",
			"Whole Grains (ounce equivalents)",
			"Refined Grains (ounce equivalents)",
			"PUFA 18:3 n-3 (alpha-linolenic acid [ALA]) (g)",
			"Solid Fats (g)" };
}
